fix: Remove CVE-2023-45857 vulnerability
southworks/botframework-cli pull request #23
Opened 2024-05-21 19:30 UTC by JhontSouth

#minor

## Description
This PR updates the version of the package **_axios_** to ^1.6.0 and avoids the [CVE-2023-45857](https://security.snyk.io/vuln/SNYK-JS-AXIOS-6032459) vulnerability.
The new _**axios**_ version required some adjustments to work with new Typescript versions as well.

## Specific Changes
  - Updated **_axios_** from 0.24.0 to ^1.6.0.
  - Updated _**@oclif/command**_ from ~1.5.19 to ~1.8.36.
  - Updated _**@types/node**_ to version ^11.3.7.
  - Updated **_ts-node_** from ^9.0.0 to ^10.8.1.
  - Updated _**typescript**_ to version ^4.9.5.
  - Fixed some code pieces to work with new TypeScript rules.
  - Added **_useUnknownInCatchVariables_** property in the _tsconfig_ files.

## Testing
The following image shows the coverage tests working after the changes.
![image](https://github.com/southworks/botframework-cli/assets/122501764/73b6264d-90fe-46db-b53c-431ca20cdd03)

2024-05-22 19:10 UTC, sw-joelmut requested changes

2024-05-22 19:10 UTC, sw-joelmut commented on packages/luis/src/api/application.ts
> +
I think these properties are related to the `Application.import` and other cases, right?, previously they were returning `any` type, but for some reason, `axios.data` returns AxiosResponse, where the parent of `data` is also an AxiosResponse. Thus, `data` shouldn't be AxiosResponse.
We shouldn't do this interface extension, either way, we could create another interface to make the function that uses `Application.import` underneath return that new interface.

2024-05-22 19:10 UTC, sw-joelmut commented on packages/luis/src/commands/luis/application/delete.ts
> +      if ('code' in result && result.code === 'Success') {
Why this change is required?, if we have to do this, ensure `result` is defined, because it could be null, and obtaining `code` property of null will fail.

2024-05-22 19:10 UTC, sw-joelmut commented on packages/luis/src/commands/luis/application/rename.ts
> +      if ('code' in appUpdateStatus && appUpdateStatus.code === 'Success') {
same here

2024-05-22 19:10 UTC, sw-joelmut commented on packages/luis/src/commands/luis/version/clone.ts
> +      const messageData = JSON.stringify(message)
Are we sure we need this step?

2024-05-22 19:10 UTC, sw-joelmut commented on packages/luis/src/commands/luis/version/delete.ts
> +      if ('code' in result && result.code === 'Success') {
same here

2024-05-22 19:10 UTC, sw-joelmut commented on packages/luis/src/commands/luis/version/export.ts
> +        this.log(flags.exportLU ? JSON.stringify(messageData) : JSON.stringify(messageData, null, 2))
same here, maybe when the AxiosResponse part is fixed, this will not be needed?

2024-05-22 19:10 UTC, sw-joelmut commented on packages/luis/src/commands/luis/version/import.ts
> +      const messageData = JSON.stringify(message)
same here

2024-05-29 12:59 UTC, sw-joelmut approved these changes

2024-05-29 18:02 UTC, JhontSouth commented
Promoted /1379

2024-05-29 18:02 UTC, closed without merging