fix: Remove CVE-2023-45133 vulnerability
southworks/botframework-cli pull request #9
Opened 2024-03-21 18:57 UTC by JhontSouth

#minor

## Description
This PR updates the versions of the packages **_nyc_** and _**@babel/traverse**_ to avoid the [CVE-2023-45133](https://security.snyk.io/vuln/SNYK-JS-BABELTRAVERSE-5962462) vulnerability.

## Specific Changes
  - Updated _**nyc**_ from 14.1.1 to 15.1.0.
  - Added rush configuration to override the _**@babel/traverse**_  version to ^7.23.2.
  - Added postinstall scripts to remove the _**@babel/traverse**_ packages that _orchestrator-core_ keeps.

## Testing
The following image shows the _botframework-cli_ pipeline working after the changes.
![image](https://github.com/microsoft/botframework-cli/assets/122501764/8c3911c2-e95e-4a03-962e-ce1464e929d8)

2024-03-22 12:56 UTC, ceciliaavila requested changes
The changes look good. Please add more details to the PR's description to understand why we are applying these changes.

2024-03-22 13:03 UTC, sw-joelmut commented on packages/cli/.nycrc
> -  "extends": "@istanbuljs/nyc-config-typescript",
Is there are reason why we are removing this extends? nyc recommends using this (https://github.com/istanbuljs/nyc?tab=readme-ov-file#typescript-projects)

2024-04-03 13:26 UTC, JhontSouth commented
@ceciliaavila @sw-joelmut 
The feedback has already been applied

2024-04-03 17:41 UTC, ceciliaavila approved these changes

2024-04-04 15:37 UTC, sw-joelmut approved these changes

2024-04-04 15:49 UTC, JhontSouth commented
Promoted /1365

2024-04-04 15:49 UTC, closed without merging